### ISSUE TITLE
w/o promt ?

### ISSUE THREAD

**Issue by wpresident** [tech-otaku/cloudflare-dns#7]
`./cf-dns.sh -d example.com -t A -n "*" -c 8.8.8.8`
i want to use it with cron. how it can be executed without promt where i must press 1 button?

**Comment by tech-otaku** [comment]
@Nuke142 

> how it can be executed without promt where i must press 1 button?

Unfortunately it can't. See comment [ Don't wait for user input]( https://github.com/tech-otaku/cloudflare-dns/issues/4#issuecomment-1189417345).

**Comment by wpresident** [comment]
Resolved by using [yes](https://man7.org/linux/man-pages/man1/yes.1.html)
`yes 1 | ./cf-dns.sh -d example.com -t A -n "*" -c 8.8.8.8`

**Comment by tech-otaku** [comment]
> yes 1 | ./cf-dns.sh -d example.com -t A -n "*" -c 8.8.8.8

This is fine if you only ever want to update the first matching record, which I assume is your use case. Others should be aware that by doing so there won't be the option to update any other matching records or add a new record.
